import os
import json
import random
from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', '..', '.env'))

from utils import (
    generate_with_single_input, 
    generate_with_multiple_input,
    generate_params_dict,
    call_llm_with_context
)

dash_line = "-" * 100

print(dash_line)
print("2 - Recap on generation functions")
print(dash_line)

print("\n\n")
print("2.1 generate_with_single_input and generate_with_multiple_input")
print(dash_line)
# The output is a dictionary with the role and content from the LLM call:
result = generate_with_single_input("Explain to me very briefly what is a Cyclotomic Polynomial. No more than 5 sentences.")
print("\n\n")
print("With generate_with_single_input")
print(dash_line)
print(result)

system_dict = {"role": 'system', 'content': 'You are a very ironic, but helpful assistant.'}
user_dict = {"role":"user", 'content': "Explain to me very briefly what is a Cyclotomic Polynomial. No more than 5 sentences."}
messages = [system_dict, user_dict]
result = generate_with_multiple_input(messages)
print("\n\n")
print("With generate_with_multiple_input")
print(dash_line)
print(result)

kwargs = {"prompt": "Write a poem about a flying rabbit.", 'top_p': 0.7, 'temperature': 1.4, 'max_tokens': 100}
result = generate_with_single_input(**kwargs)
print("\n\n")
print("With generate_with_single_input using kwargs")
print(dash_line)
print(result)

print("\n\n")
print("2.2 Generating a kwargs with desired parameters")
print(dash_line)

kwargs = generate_params_dict("Solve 2x + 1 = 0.")
print(kwargs)

# Passing it to the LLM
result = generate_with_single_input(**kwargs)
print("\n\n")
print("With generate_with_single_input using kwargs generated by generate_params_dict")
print(dash_line)
print(result['content'])

print("\n\n")
print("2.3 Allowing the LLM to keep a conversation")
print(dash_line)

# Example usage
context = [{"role": 'system', 'content': 'You are an ironic but helpful assistant.'}, 
           {'role': 'assistant', 'content': "How can I help you, majesty?"}]
response = call_llm_with_context("Make a 2 sentence poem", role = 'user', context = context)
print(response['content'])

# Let's inspect now the context list
print(context)

# Now we can keep the conversation
response = call_llm_with_context("Now add two more sentences.", context = context)
print(response['content'])

print("\n\n")
print(dash_line)
print("3 - Understanding the Parameters")
print(dash_line)

print("\n\n")
print("3.2 Nucleus Sampling - top_p")
print(dash_line)
query = "In one sentence, explain to me what is RAG (Retrieval Augmented Generation)."
# Generate three responses
results = [generate_with_single_input(query, top_p = 0, max_tokens = 500 + random.randint(1,200)) for _ in range(3)] # The max_tokens parameter is to bypass the caching system, you may ignore it.
for i,result in enumerate(results):
    print(f"Call number {i+1}:\nResponse: {result['content']}")


# Generate three responses
results = [generate_with_single_input(query, top_p = 0.8, max_tokens = 500 + random.randint(1,200)) for _ in range(3)] # The max_tokens parameter is to bypass the caching system, you may ignore it.
for i,result in enumerate(results):
    print(f"Call number {i+1}:\nResponse: {result['content']}")


print("\n\n")
print("3.3 Top-k sampling")
print(dash_line)

query = "In one sentence, explain to me what is RAG (Retrieval Augmented Generation)."
# Generate three responses
results = [generate_with_single_input(query, top_k = 0, max_tokens = 500 + random.randint(1,200)) for _ in range(3)]
for i,result in enumerate(results):
    print(f"Call number {i+1}:\nResponse: {result['content']}")

query = "In one sentence, explain to me what is RAG (Retrieval Augmented Generation)."
# Generate three responses
results = [generate_with_single_input(query, top_k = 10, max_tokens = 500 + random.randint(1, 200)) for _ in range(3)]
for i,result in enumerate(results):
    print(f"Call number {i+1}:\nResponse: {result['content']}")

print("\n\n")
print("3.4 Temperature")
print(dash_line)

# Generate three responses
results = [generate_with_single_input(query, temperature = t) for t in [0.3, 1.5, 2]]
print(f"Query: {query}")
for i,(result,temperature) in enumerate(zip(results, [0.3,1.5,2])):
    print(f"\033[1mCall number {i+1}.\033[0m \033[1mTemperature = {temperature}\033[0m\nResponse: {result['content']}\n\n\n")


# Generate three responses
query = "Write a small poem about a flying rabbit."
params = ((0.3, 0.8), (1.5, 0.5), (2, 0.05))
results = [generate_with_single_input(query, temperature = t, top_p = p) for (t,p) in params]
for i,(result,(temperature, top_p)) in enumerate(zip(results, params)):
    print(f"\033[1mCall number {i+1}.\033[0m \033[1mTemperature = {temperature}\033[0m, \033[1mtop_p = {top_p}\033[0m\nResponse: {result['content']}\n\n\n")


print("\n\n")
print("3.5 Repetition penalty")
print(dash_line)
# Generate three responses
query = "List healthy breakfast options."

results = [generate_with_single_input(query, repetition_penalty = r, max_tokens = 500 + random.randint(1,200)) for r in [None, 1.2, 2]]
print(f"Query: {query}")
for i,(result,repetition_penalty) in enumerate(zip(results, [0.3,1.5,2])):
    print(f"\033[1mCall number {i+1}.\033[0m \033[1mRepetition Penalty = {repetition_penalty}\033[0m\nResponse: {result['content']}\n\n\n")
